# Generated by Django 3.2.4 on 2021-07-01 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Title of your Advertisement"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="USD", max_length=15, verbose_name="Daily Price"
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="Location")),
                ("brand", models.CharField(max_length=20, verbose_name="Brand")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                ("year", models.CharField(max_length=4, verbose_name="Year")),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("Oil", "Oil"),
                            ("Disel", "Disel"),
                            ("LPG", "LPG"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=20,
                        verbose_name="Fuel",
                    ),
                ),
                (
                    "gear",
                    models.CharField(
                        choices=[("Auto", "Auto"), ("Manuel", "Manuel")],
                        max_length=20,
                        verbose_name="Gear",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Explanation")),
                (
                    "pics_of_car",
                    models.ImageField(
                        blank=True, upload_to="uploads/", verbose_name="Upload Images"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Mobile Phone",
                        max_length=40,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Proclamation Date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForsaleCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Title of your Advertisement"
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="USD", max_length=15, verbose_name="Price"
                    ),
                ),
                ("location", models.CharField(max_length=30, verbose_name="Location")),
                ("brand", models.CharField(max_length=20, verbose_name="Brand")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                ("year", models.CharField(max_length=4, verbose_name="Year")),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("Oil", "Oil"),
                            ("Disel", "Disel"),
                            ("LPG", "LPG"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=20,
                        verbose_name="Fuel",
                    ),
                ),
                (
                    "exchange",
                    models.BooleanField(
                        default=None, verbose_name="Exchange Available"
                    ),
                ),
                (
                    "gear",
                    models.CharField(
                        choices=[("Auto", "Auto"), ("Manuel", "Manuel")],
                        max_length=20,
                        verbose_name="Gear",
                    ),
                ),
                (
                    "statue",
                    models.CharField(
                        choices=[
                            ("First Hand", "First Hand"),
                            ("Second Hand", "Second Hand"),
                        ],
                        max_length=30,
                        verbose_name="Statue",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Explanation")),
                (
                    "pics_of_car",
                    models.ImageField(
                        blank=True, upload_to="uploads/", verbose_name="Upload Images"
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        help_text="Mobile Phone",
                        max_length=40,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Proclamation Date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
