# Generated by Django 3.2.4 on 2021-07-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forsalecar",
            name="pics_of_car",
            field=models.ImageField(
                blank=True, upload_to="forsalecar/", verbose_name="Upload Images"
            ),
        ),
        migrations.AlterField(
            model_name="rentalcar",
            name="pics_of_car",
            field=models.ImageField(
                blank=True, upload_to="rentalcar/", verbose_name="Upload Images"
            ),
        ),
    ]
