# Generated by Django 3.2.4 on 2021-07-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0003_auto_20210702_1309"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rentalcar",
            options={"ordering": ["title"]},
        ),
    ]
