# Generated by Django 3.2.4 on 2021-07-03 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicle", "0004_alter_rentalcar_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rentcarphoto",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="vehicle.rentalcar"
            ),
        ),
    ]
