# Generated by Django 3.2.4 on 2021-07-05 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="rentHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Title of your Advertisement"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="USD", max_length=15, verbose_name="Daily Price"
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Age of your Building")),
                (
                    "sqm",
                    models.CharField(
                        help_text="m²", max_length=5, verbose_name="Area/Squaremeter"
                    ),
                ),
                (
                    "heating",
                    models.CharField(
                        choices=[
                            ("Central System", "Central System"),
                            ("Solar Panel", "Solar Panel"),
                            ("Air Conditioner", "Air Conditioner"),
                            ("Electricity", "Electricity"),
                            ("None", "None"),
                        ],
                        max_length=30,
                        verbose_name="Heating Type",
                    ),
                ),
                (
                    "room",
                    models.CharField(max_length=5, verbose_name="Number of your Rooms"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Suite", "Suite"),
                            ("Villa", "Villa"),
                            ("Building", "Building"),
                        ],
                        max_length=30,
                        verbose_name="Type of your estate",
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="Level/floor of your room")),
                (
                    "housekeeper",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=5,
                        verbose_name="Is there a housekeeper?",
                    ),
                ),
                (
                    "pay_due",
                    models.CharField(
                        help_text="USD",
                        max_length=5,
                        verbose_name="Montly Subscription Fee",
                    ),
                ),
                (
                    "mobel",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=5,
                        verbose_name="With mobel?",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="USD", max_length=15, verbose_name="Price"
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="Explanation")),
                (
                    "contact",
                    models.CharField(
                        help_text="Mobile Phone",
                        max_length=40,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Proclamation Date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="saleHouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Title of your Advertisement"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="USD", max_length=15, verbose_name="Daily Price"
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Age of your Building")),
                (
                    "sqm",
                    models.CharField(
                        help_text="m²", max_length=5, verbose_name="Area/Squaremeter"
                    ),
                ),
                (
                    "heating",
                    models.CharField(
                        choices=[
                            ("Central System", "Central System"),
                            ("Solar Panel", "Solar Panel"),
                            ("Air Conditioner", "Air Conditioner"),
                            ("Electricity", "Electricity"),
                            ("None", "None"),
                        ],
                        max_length=30,
                        verbose_name="Heating Type",
                    ),
                ),
                (
                    "room",
                    models.CharField(max_length=5, verbose_name="Number of your Rooms"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("Suite", "Suite"),
                            ("Villa", "Villa"),
                            ("Building", "Building"),
                        ],
                        max_length=30,
                        verbose_name="Type of your estate",
                    ),
                ),
                ("floor", models.IntegerField(verbose_name="Level/floor of your room")),
                (
                    "housekeeper",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=5,
                        verbose_name="Is there a housekeeper?",
                    ),
                ),
                (
                    "pay_due",
                    models.CharField(
                        help_text="USD",
                        max_length=5,
                        verbose_name="Montly Subscription Fee",
                    ),
                ),
                (
                    "mobel",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")],
                        max_length=5,
                        verbose_name="With mobel?",
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        help_text="USD",
                        max_length=15,
                        verbose_name="Monthly Rent Price",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="Explanation")),
                (
                    "contact",
                    models.CharField(
                        help_text="Mobile Phone",
                        max_length=40,
                        verbose_name="Contact Info",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Proclamation Date"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SaleHousePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="salehouses/"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="housing.salehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentHousePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(blank=True, null=True, upload_to="renthouses/"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="housing.renthouse",
                    ),
                ),
            ],
        ),
    ]
