# Generated by Django 3.2.4 on 2021-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="renthouse",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="salehouse",
            options={"ordering": ["title"]},
        ),
        migrations.AlterField(
            model_name="renthouse",
            name="location",
            field=models.CharField(
                help_text="USD", max_length=100, verbose_name="Location"
            ),
        ),
        migrations.AlterField(
            model_name="renthouse",
            name="price",
            field=models.CharField(
                help_text="USD", max_length=15, verbose_name="Monthly Price"
            ),
        ),
        migrations.AlterField(
            model_name="renthousephoto",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="renthouses/",
                verbose_name="Upload Images",
            ),
        ),
        migrations.AlterField(
            model_name="salehouse",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="salehouse",
            name="price",
            field=models.CharField(
                help_text="USD", max_length=15, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="salehousephoto",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="salehouses/",
                verbose_name="Upload Images",
            ),
        ),
    ]
